- id: lint-system-design-format
  name: Lint Autoware System Design Format
  description: Lint autoware system design format YAML files (.node.yaml, .module.yaml, .system.yaml, .parameter_set.yaml)
  entry: python3 autoware_system_designer/autoware_system_designer/linter/run_lint.py
  language: python
  additional_dependencies: [PyYAML, Jinja2]
  files: \.(node|module|system|parameter_set)\.yaml$
